# PostgreSQL. Versions 9.3 and up are supported.
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db                # ← Docker の DB サービス名
  port: 5432
  username: root      # ← docker-compose.yml の POSTGRES_USER と合わせる
  password: password      # ← docker-compose.yml の POSTGRES_PASSWORD と合わせる

development:
  <<: *default
  database: toretate_marche_development

test:
  <<: *default
  database: toretate_marche_test

production:
  <<: *default
  database: toretate_marche_production
  username: toretate_marche
  password: <%= ENV["TORETATE_MARCHE_DATABASE_PASSWORD"] %>
